### ISSUE TITLE
Test what happens when creating a new project on top of existing directory

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#130]
New App Engine Wizard
e.g. when deleted old project from eclipse but not file system

**Comment by elharo** [comment]
Answer, surprisingly, is an IllegalArgumentException. Elevating this to a bug.


!ENTRY todo plugin ID 4 1 2016-05-17 10:55:53.153
!MESSAGE Failed to create project
!STACK 0
java.lang.IllegalArgumentException
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectWorkingCopy.setProjectFacetActionConfig(FacetedProjectWorkingCopy.java:1629)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$1.run(FacetedProject.java:320)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modify(FacetedProject.java:339)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.installProjectFacet(FacetedProject.java:255)
	at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProject.installJavaFacet(CreateAppEngineStandardWtpProject.java:95)
	at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProject.execute(CreateAppEngineStandardWtpProject.java:75)
	at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:108)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:130)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
