### ISSUE TITLE
NullPointerException in CloudSdkLaunchConfigurationDelegate

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#159]
Not clear when this occurs:

ENTRY org.eclipse.core.jobs 4 2 2016-05-11 15:12:36.058
!MESSAGE An internal error occurred during: "Starting App Engine Standard at localhost".
!STACK 0
java.lang.NullPointerException
	at com.google.cloud.tools.eclipse.appengine.localserver.server.CloudSdkLaunchConfigurationDelegate.getRunnable(CloudSdkLaunchConfigurationDelegate.java:172)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.CloudSdkLaunchConfigurationDelegate.launch(CloudSdkLaunchConfigurationDelegate.java:73)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:731)
	at org.eclipse.wst.server.core.internal.Server.startImpl2(Server.java:3556)
	at org.eclipse.wst.server.core.internal.Server.startImpl(Server.java:3492)
	at org.eclipse.wst.server.core.internal.Server$StartJob.run(Server.java:367)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SESSION 2016-05-11 15:45:29.953 -----------------------------------------------
eclipse.buildId=unknown

**Comment by elharo** [comment]
This happens when, in Eclipse with the plugin, you "Context Menu > Run As > Run on server" with the new, non-GSF runtime

**Comment by rdayal** [comment]
Can you guys break out which issues have to do with GSF vs. non-GSF? Maybe just edit the issue title to reflect that.

**Comment by akerekes** [comment]
Is this still valid?
