### ISSUE TITLE
IllegalArgumentException when defining new project with StandardProjectWizard

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/gcloud-eclipse-tools#161]
I get an exception if I create a project using the native new AE project wizard when I haven’t defined a runtime using the code on the [wizard branch](dc29c80ef3b01d142b238daab1209001a0a1aa8c).  We need to create a runtime instance if necessary.  `StandardProjectWizard#canFinish()` should return false when there is no valid runtime, and either add a new wizard page or at least prompt at some point in the process.

```
java.lang.IllegalArgumentException: Runtime App Engine has not been defined.
at org.eclipse.wst.common.project.facet.core.runtime.internal.RuntimeManagerImpl.getRuntime(RuntimeManagerImpl.java:210)
at org.eclipse.wst.common.project.facet.core.runtime.RuntimeManager.getRuntime(RuntimeManager.java:120)
at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProject.installAppEngineRuntime(CreateAppEngineStandardWtpProject.java:114)
at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProject.execute(CreateAppEngineStandardWtpProject.java:81)
at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:108)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:130)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by elharo** [comment]
I've suppressed the IllegalArgumentException. Now we need to figure out how to programmatically attach a runtime if the one we want is not already there.

**Comment by elharo** [comment]
I think we're going to need to set this up in the wizard since even if we can configure it programmatically, we still need to ask the user for the various properties, most importantly the location of the gcloud SDK.

**Comment by briandealwis** [comment]
Note that if we pull the runtime (compile-time) jars from the AppEngine SDK / Maven Central, then the use of GCloud is needed only in the local debug server and deployment story.

**Comment by rdayal** [comment]
Did you guys figure out what you want to do here?

Is this actually an enhancement? If there's no runtime associated with this on import, isn't this a broken project?

**Comment by elharo** [comment]
Yes, if there's no runtime it's a broken project.

What I'd like to do is create a runtime if it doesn't already exist. I haven't yet deduced the magic incantations to make that happen. I think I need to trace through Eclipse and see what code it's invoking when it creates one of these.

**Comment by rdayal** [comment]
@nbashirbello may know something about this.

**Comment by elharo** [comment]
The only remaining piece of this is to autolocate the SDK which we're tracking in a separate issue #10
