### ISSUE TITLE
GSF server cannot load classes

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#193]
To reproduce (after fixing #181)

1. Create a new application using the wizard
2. "Run on Server" from the context menu

probably need to adjust build path or classpath some way.

INFO     2016-05-23 14:20:17,098 devappserver2.py:769] Skipping SDK update check.
INFO     2016-05-23 14:20:17,221 api_server.py:205] Starting API server at: http://localhost:65152
INFO     2016-05-23 14:20:17,250 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2016-05-23 14:20:17,253 admin_server.py:116] Starting admin server at: http://localhost:8000
May 23, 2016 2:20:18 PM com.google.appengine.tools.development.AbstractContainerService configure
WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)
May 23, 2016 2:20:19 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger
May 23, 2016 2:20:19 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: jetty-6.1.x
May 23, 2016 2:20:19 PM com.google.apphosting.utils.jetty.JettyLogger warn
WARNING: EXCEPTION 
java.lang.ClassNotFoundException: c.f.HelloAppEngine
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:199)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.mortbay.util.Loader.loadClass(Loader.java:91)
	at org.mortbay.util.Loader.loadClass(Loader.java:71)
	at org.mortbay.jetty.servlet.Holder.doStart(Holder.java:73)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:242)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.appengine.tools.development.JettyContainerService.startContainer(JettyContainerService.java:271)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:242)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:56)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:208)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:206)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:128)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:82)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:48)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:66)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:44)

May 23, 2016 2:20:19 PM com.google.appengine.tools.development.devappserver2.RemoteApiDelegate log
SEVERE: [1464013219699000] javax.servlet.ServletContext log: unavailable
javax.servlet.UnavailableException: c.f.HelloAppEngine
	at org.mortbay.jetty.servlet.Holder.doStart(Holder.java:79)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:242)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.appengine.tools.development.JettyContainerService.startContainer(JettyContainerService.java:271)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:242)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:56)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:208)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:206)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:128)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:82)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:48)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:66)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:44)

May 23, 2016 2:20:19 PM com.google.apphosting.utils.jetty.JettyLogger warn
WARNING: failed HelloAppEngine: java.lang.NullPointerException
May 23, 2016 2:20:19 PM com.google.apphosting.utils.jetty.JettyLogger warn
WARNING: Failed startup of context com.google.appengine.tools.development.DevAppEngineWebAppContext@436a4e4b{/,/Users/elharo/runtime-EclipseApplication/test/src/main/webapp}
java.lang.NullPointerException
	at java.lang.Class.isAssignableFrom(Native Method)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.appengine.tools.development.JettyContainerService.startContainer(JettyContainerService.java:271)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:242)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:56)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:208)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:206)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:128)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:82)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:48)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:66)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:44)

May 23, 2016 2:20:19 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Started SelectChannelConnector@localhost:65154
May 23, 2016 2:20:19 PM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:65154/
May 23, 2016 2:20:19 PM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:65154/_ah/admin
May 23, 2016 2:20:19 PM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart
INFO: Dev App Server is now running
INFO     2016-05-23 14:20:21,801 module.py:788] default: "GET / HTTP/1.1" 503 1288
INFO     2016-05-23 14:20:25,466 module.py:788] default: "GET /test/ HTTP/1.1" 503 1293
May 23, 2016 2:20:23 PM com.google.appengine.tools.development.AbstractContainerService configure
WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)
May 23, 2016 2:20:23 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger
May 23, 2016 2:20:23 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: jetty-6.1.x
May 23, 2016 2:20:24 PM com.google.apphosting.utils.jetty.JettyLogger warn
WARNING: EXCEPTION 
java.lang.ClassNotFoundException: c.f.HelloAppEngine
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:199)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.mortbay.util.Loader.loadClass(Loader.java:91)
	at org.mortbay.util.Loader.loadClass(Loader.java:71)
	at org.mortbay.jetty.servlet.Holder.doStart(Holder.java:73)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:242)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.appengine.tools.development.JettyContainerService.startContainer(JettyContainerService.java:271)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:242)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:56)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:208)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:206)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:128)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:82)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:48)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:66)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:44)

May 23, 2016 2:20:24 PM com.google.appengine.tools.development.devappserver2.RemoteApiDelegate log
SEVERE: [1464013224535000] javax.servlet.ServletContext log: unavailable
javax.servlet.UnavailableException: c.f.HelloAppEngine
	at org.mortbay.jetty.servlet.Holder.doStart(Holder.java:79)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:242)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.appengine.tools.development.JettyContainerService.startContainer(JettyContainerService.java:271)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:242)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:56)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:208)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:206)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:128)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:82)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:48)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:66)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:44)

May 23, 2016 2:20:24 PM com.google.apphosting.utils.jetty.JettyLogger warn
WARNING: failed HelloAppEngine: java.lang.NullPointerException
May 23, 2016 2:20:24 PM com.google.apphosting.utils.jetty.JettyLogger warn
WARNING: Failed startup of context com.google.appengine.tools.development.DevAppEngineWebAppContext@436a4e4b{/,/Users/elharo/runtime-EclipseApplication/test/src/main/webapp}
java.lang.NullPointerException
	at java.lang.Class.isAssignableFrom(Native Method)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.appengine.tools.development.JettyContainerService.startContainer(JettyContainerService.java:271)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:242)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:56)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:208)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:206)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:128)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:82)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:48)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:66)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:44)

May 23, 2016 2:20:24 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Started SelectChannelConnector@localhost:65161
May 23, 2016 2:20:24 PM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:65161/
May 23, 2016 2:20:24 PM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:65161/_ah/admin
May 23, 2016 2:20:24 PM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart
INFO: Dev App Server is now running
INFO     2016-05-23 14:20:26,306 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 503 1298

**Comment by elharo** [comment]
I can reproduce this running at the command line:

$ /Users/elharo/google-cloud-sdk/bin/dev_appserver.py --port 8080 --jvm_flag=-Dappengine.user.timezone=UTC src/main/webapp

Thus I suspect this is not correctly setting up the command to run the local server.

**Comment by elharo** [comment]
I can make it work by manually copying the classes out of build/classes into src/main/webapp/WEB-INF/classes so this confirms it's a classpath issue.
This bug now becomes a question of figuring out how to configure eclipse and jetty/dev_appserver so the classes that eclipse generates show up in the right place where Jetty looks for them.

**Comment by elharo** [comment]
I think we're going to need to do one of two things:

A) set up a the generic publisher deploy ant task to build the war and move it where dev_appserver will pick it up (assuming dev_appserver notices that sort of thing)

or

B) write a wrapper for dev_appserver that first builds the war and then launches dev_appserver pointing to that war (if dev_appserver doesn't support hot deploy)

**Comment by rdayal** [comment]
This seems to be a high priority.

**Comment by elharo** [comment]
obsolete
