### ISSUE TITLE
Unresolved requirement: Require-Bundle: com.google.cloud.tools.eclipse.appengine.ui; bundle-version

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#203]
When trying to run local server off master:

org.osgi.framework.BundleException: Could not resolve module: com.google.cloud.tools.eclipse.appengine.localserver [1044]
  Unresolved requirement: Require-Bundle: com.google.cloud.tools.eclipse.appengine.ui; bundle-version="0.1.0"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by elharo** [comment]
local eclipse config problem; no code changes requied
