### ISSUE TITLE
Flaky failures in CloudSdkContextFunctionTest

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#296]
This only seems to happen some of the time: 

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.google.cloud.tools.eclipse.sdk.internal.CloudSdkContextFunctionTest
Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.393 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.sdk.internal.CloudSdkContextFunctionTest
testContextFunctionReinvoked(com.google.cloud.tools.eclipse.sdk.internal.CloudSdkContextFunctionTest)  Time elapsed: 0.292 sec  <<< FAILURE!
java.lang.AssertionError: expected null, but was:<com.google.cloud.tools.appengine.cloudsdk.CloudSdk@76154f34>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at org.junit.Assert.assertNull(Assert.java:747)
	at com.google.cloud.tools.eclipse.sdk.internal.CloudSdkContextFunctionTest.testContextFunctionReinvoked(CloudSdkContextFunctionTest.java:81)

testRetrieveWithLocation(com.google.cloud.tools.eclipse.sdk.internal.CloudSdkContextFunctionTest)  Time elapsed: 0.029 sec
testNoLocationFails(com.google.cloud.tools.eclipse.sdk.internal.CloudSdkContextFunctionTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: expected:<java.lang.Object@1c9e95a> but was:<com.google.cloud.tools.appengine.cloudsdk.CloudSdk@6ef714a0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.google.cloud.tools.eclipse.sdk.internal.CloudSdkContextFunctionTest.testNoLocationFails(CloudSdkContextFunctionTest.java:62)

Running com.google.cloud.tools.eclipse.sdk.internal.CloudSdkProviderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in com.google.cloud.tools.eclipse.sdk.internal.CloudSdkProviderTest
testSetPreferenceInvalid(com.google.cloud.tools.eclipse.sdk.internal.CloudSdkProviderTest)  Time elapsed: 0.007 sec

Results :

Failed tests: 
  CloudSdkContextFunctionTest.testContextFunctionReinvoked:81 expected null, but was:<com.google.cloud.tools.appengine.cloudsdk.CloudSdk@76154f34>
  CloudSdkContextFunctionTest.testNoLocationFails:62 expected:<java.lang.Object@1c9e95a> but was:<com.google.cloud.tools.appengine.cloudsdk.CloudSdk@6ef714a0>

**Comment by elharo** [comment]
mvn clean test

seems to work but

mvn clean install does not

**Comment by elharo** [comment]
Believe this flakiness to be related to setting global static state in tests. Working on injecting preferences instead.

**Comment by elharo** [comment]
appears to be fixed
