### ISSUE TITLE
Incompatibility with appengine-gcs-client

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/gcloud-eclipse-tools#598]
Hello,
I have an implementation with appengine-gcs-client which I'm using to use a transparent code for both development and production environment.
```
<dependency>
    <groupId>com.google.appengine.tools</groupId>
    <artifactId>appengine-gcs-client</artifactId>
    <version>0.6</version>
</dependency>
```

The code is pretty simple
```
GcsService createGcsService = GcsServiceFactory.createGcsService();
GcsOutputChannel createOrReplace = createGcsService.createOrReplace(storageObject, GcsFileOptions.getDefaultInstance());

try (OutputStream newOutputStream = Channels.newOutputStream(createOrReplace)) {
    IOUtils.write(json.toString().getBytes("UTF-8"), newOutputStream);
}
```

But it seems there is some incompatibility problem, as you can read from the server log
```
ago 22, 2016 7:44:08 AM com.google.appengine.repackaged.org.apache.commons.httpclient.SimpleHttpConnectionManager getConnectionWithTimeout

AVVERTENZA: SimpleHttpConnectionManager being used incorrectly.  Be sure that HttpMethod.releaseConnection() is always called and that only one thread and/or method is using this connection manager at a time.

ago 22, 2016 7:44:08 AM com.google.appengine.tools.cloudstorage.RetryHelper doRetry

INFORMAZIONI: RetryHelper(1.570 ms, 1 attempts, com.google.appengine.tools.cloudstorage.GcsServiceImpl$1@8111e8c): Attempt #1 failed [java.io.IOException: java.lang.NoSuchMethodException: com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate.getService(java.lang.String)], sleeping for 1231 ms

ago 22, 2016 7:44:09 AM com.google.appengine.tools.cloudstorage.RetryHelper doRetry

INFORMAZIONI: RetryHelper(1.236 s, 2 attempts, com.google.appengine.tools.cloudstorage.GcsServiceImpl$1@8111e8c): Attempt #2 failed [java.io.IOException: java.lang.NoSuchMethodException: com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate.getService(java.lang.String)], sleeping for 2329 ms

ago 22, 2016 7:44:12 AM com.google.appengine.tools.cloudstorage.RetryHelper doRetry

INFORMAZIONI: RetryHelper(3.565 s, 3 attempts, com.google.appengine.tools.cloudstorage.GcsServiceImpl$1@8111e8c): Attempt #3 failed [java.io.IOException: java.lang.NoSuchMethodException: com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate.getService(java.lang.String)], sleeping for 4260 ms

ago 22, 2016 7:44:16 AM com.google.appengine.tools.cloudstorage.RetryHelper doRetry

INFORMAZIONI: RetryHelper(7.826 s, 4 attempts, com.google.appengine.tools.cloudstorage.GcsServiceImpl$1@8111e8c): Attempt #4 failed [java.io.IOException: java.lang.NoSuchMethodException: com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate.getService(java.lang.String)], sleeping for 6098 ms

ago 22, 2016 7:44:22 AM com.google.appengine.tools.cloudstorage.RetryHelper doRetry

INFORMAZIONI: RetryHelper(13.92 s, 5 attempts, com.google.appengine.tools.cloudstorage.GcsServiceImpl$1@8111e8c): Attempt #5 failed [java.io.IOException: java.lang.NoSuchMethodException: com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate.getService(java.lang.String)], sleeping for 14554 ms

ago 22, 2016 7:44:36 AM com.google.apphosting.utils.jetty.JettyLogger warn

AVVERTENZA: /

com.google.appengine.tools.cloudstorage.RetriesExhaustedException: RetryHelper(28.48 s, 6 attempts, com.google.appengine.tools.cloudstorage.GcsServiceImpl$1@8111e8c): Too many failures, giving up

	at com.google.appengine.tools.cloudstorage.RetryHelper.doRetry(RetryHelper.java:127)

	at com.google.appengine.tools.cloudstorage.RetryHelper.runWithRetries(RetryHelper.java:166)

	at com.google.appengine.tools.cloudstorage.RetryHelper.runWithRetries(RetryHelper.java:156)

	at com.google.appengine.tools.cloudstorage.GcsServiceImpl.createOrReplace(GcsServiceImpl.java:70)

	at it.noovle.ape.dev.TimeDebugger.save(TimeDebugger.java:155)

	at it.noovle.ape.filter.ApeHttpFilter.doFilter(ApeHttpFilter.java:113)

	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)

	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)

	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)

	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)

	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)

	at com.google.appengine.tools.development.devappserver2.RequestIdFilter.doFilter(RequestIdFilter.java:36)

	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)

	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)

	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)

	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)

	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)

	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)

	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)

	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)

	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)

	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)

	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)

	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)

	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)

	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)

	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)

	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)

	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:511)

	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)

	at org.mortbay.jetty.Server.handle(Server.java:326)

	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)

	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)

	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)

	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)

	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)

	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)

	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

Caused by: java.io.IOException: java.lang.NoSuchMethodException: com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate.getService(java.lang.String)

	at com.google.appengine.tools.cloudstorage.dev.LocalRawGcsService$BlobStorageAdapter.getInstance(LocalRawGcsService.java:186)

	at com.google.appengine.tools.cloudstorage.dev.LocalRawGcsService$BlobStorageAdapter.access$000(LocalRawGcsService.java:109)

	at com.google.appengine.tools.cloudstorage.dev.LocalRawGcsService.ensureInitialized(LocalRawGcsService.java:194)

	at com.google.appengine.tools.cloudstorage.dev.LocalRawGcsService.beginObjectCreation(LocalRawGcsService.java:249)

	at com.google.appengine.tools.cloudstorage.dev.LocalRawGcsService.beginObjectCreation(LocalRawGcsService.java:92)

	at com.google.appengine.tools.cloudstorage.GcsServiceImpl$1.call(GcsServiceImpl.java:74)

	at com.google.appengine.tools.cloudstorage.GcsServiceImpl$1.call(GcsServiceImpl.java:70)

	at com.google.appengine.tools.cloudstorage.RetryHelper.doRetry(RetryHelper.java:108)

	... 37 more

Caused by: java.lang.NoSuchMethodException: com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate.getService(java.lang.String)

	at java.lang.Class.getDeclaredMethod(Class.java:2130)

	at com.google.appengine.tools.cloudstorage.dev.LocalRawGcsService$BlobStorageAdapter.<init>(LocalRawGcsService.java:123)

	at com.google.appengine.tools.cloudstorage.dev.LocalRawGcsService$BlobStorageAdapter.getInstance(LocalRawGcsService.java:184)

	... 44 more
```

And here is the final stack trace
```
com.google.appengine.tools.cloudstorage.RetriesExhaustedException: RetryHelper(28.48 s, 6 attempts, com.google.appengine.tools.cloudstorage.GcsServiceImpl$1@8111e8c): Too many failures, giving up
	at com.google.appengine.tools.cloudstorage.RetryHelper.doRetry(RetryHelper.java:127)
	at com.google.appengine.tools.cloudstorage.RetryHelper.runWithRetries(RetryHelper.java:166)
	at com.google.appengine.tools.cloudstorage.RetryHelper.runWithRetries(RetryHelper.java:156)
	at com.google.appengine.tools.cloudstorage.GcsServiceImpl.createOrReplace(GcsServiceImpl.java:70)
```

Needless to say, with the previous plugin I never saw this kind of error, it works w/o problems.

**Comment by NicolaSpreafico** [comment]
Opened twice due to network error.
You can delete it.

Sorry
